"""initial_schema

Revision ID: a50917b77cf4
Revises: 
Create Date: 2026-04-22 13:39:23.071837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50917b77cf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_folder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_name'), ['name'], unique=False)

    op.create_table('ingestionprogress',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('job',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_collection_id'), ['collection_id'], unique=False)

    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_label'), ['label'], unique=False)

    op.create_table('reviewrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('unreviewed', 'confirmed', 'overridden', 'flagged', name='reviewstatus'), nullable=False),
    sa.Column('override_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewrecord_item_id'), ['item_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewrecord_item_id'))

    op.drop_table('reviewrecord')
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_label'))
        batch_op.drop_index(batch_op.f('ix_prediction_item_id'))

    op.drop_table('prediction')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_collection_id'))

    op.drop_table('item')
    op.drop_table('job')
    op.drop_table('ingestionprogress')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_name'))

    op.drop_table('collection')
    # ### end Alembic commands ###
